name: Crowdin

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch: {}

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repo
        uses: actions/checkout@v2
      - name: Crowdin
        uses: crowdin/github-action@1.3.1
        with:
          upload_translations: true
          download_translations: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
